import type { GalerieEntry } from "./Galerie";

export const BEISPIEL_SCHWELLE = 10;

const base = {
  fotos:                  [] as GalerieEntry["fotos"],
  hat_botschaft:          false  as const,
  zuletzt_gesehen_am:     null,
  foto_frueher_key:       null,
  foto_frueher_jahr:      null,
  foto_heute_key:         null,
  foto_heute_jahr:        null,
  istBeispiel:            true   as const,
  istLeerRahmen:          false  as const,
};

export const BEISPIEL_PROFILE: GalerieEntry[] = [
  {
    id: -1, anmeldung_ticket_id: -1,
    anzeige_name: "Renate",
    vorstellung: "Hüterin der Schallplatte. Wenn sie »Ich Will Alles« auflegt, tanzen alle noch mal.",
    lauter_song:   "Nena — 99 Luftballons",
    f_tontraeger:  "Schallplatte",
    f_abends:      "Disko / Club",
    f_untersatz:   "Fahrrad",
    f_musik:       "Neue Deutsche Welle",
    f_getraenk:    "Weinschorle",
    ...base,
  },
  {
    id: -2, anmeldung_ticket_id: -2,
    anzeige_name: "Manfred",
    vorstellung: "Kennt jede Theke am Niederrhein. 1985 war er gerade verliebt — und man merkt's noch.",
    lauter_song:   "Herbert Grönemeyer — Männer",
    f_tontraeger:  "Kassette",
    f_abends:      "Kneipe",
    f_untersatz:   "Moped/Motorrad",
    f_musik:       "Rock / Metal",
    f_getraenk:    "Bier",
    ...base,
  },
  {
    id: -3, anmeldung_ticket_id: -3,
    anzeige_name: "Gisela",
    vorstellung: "Auf der Tanzfläche unschlagbar. Sekt in der Hand, Disco im Blut, Stöckelschuh im Takt.",
    lauter_song:   "ABBA — Dancing Queen",
    f_tontraeger:  "Schallplatte",
    f_abends:      "Disko / Club",
    f_untersatz:   "Bus & Bahn",
    f_musik:       "Pop",
    f_getraenk:    "Sekt / Prosecco",
    ...base,
  },
  {
    id: -4, anmeldung_ticket_id: -4,
    anzeige_name: "Wolfgang",
    vorstellung: "Kennt alle Strophen. Alle. Hält auf Partys gern kleine Konzerte — ungefragt.",
    lauter_song:   "Beethoven — Schicksalssinfonie",
    f_tontraeger:  "CD",
    f_abends:      "Konzert",
    f_untersatz:   "Auto",
    f_musik:       "Klassik",
    f_getraenk:    "Rotwein",
    ...base,
  },
  {
    id: -5, anmeldung_ticket_id: -5,
    anzeige_name: "Helga",
    vorstellung: "»Alles irgendwie.« Seit 40 Jahren Stammgast. Bestellt einen Softdrink und gibt die Runde.",
    lauter_song:   "Böhse Onkelz — Nur die Besten sterben jung",
    f_tontraeger:  "MP3-Player",
    f_abends:      "Kneipe",
    f_untersatz:   "Zu Fuß",
    f_musik:       "Alles irgendwie",
    f_getraenk:    "Softdrink / Wasser",
    ...base,
  },
];

export const LEER_RAHMEN: GalerieEntry = {
  id:                     -99,
  anmeldung_ticket_id:    -99,
  anzeige_name:           "Dein Platz an der Wand",
  vorstellung:            null,
  lauter_song:            null,
  f_tontraeger:           null,
  f_abends:               null,
  f_untersatz:            null,
  f_musik:                null,
  f_getraenk:             null,
  fotos:                  [],
  hat_botschaft:          false,
  zuletzt_gesehen_am:     null,
  foto_frueher_key:       null,
  foto_frueher_jahr:      null,
  foto_heute_key:         null,
  foto_heute_jahr:        null,
  istBeispiel:            false,
  istLeerRahmen:          true,
};
