export const PHASE2_CONFIG = {
  ANMELDUNG_AKTIV: false,
  PHASE1_BEENDET: true,

  ANMELDEFRIST: "Dienstag, 30. Juni 2026",
  ANMELDEFRIST_KURZ: "30.06.2026",
  PREIS_PRO_PERSON: 10,
  PAYPAL_LINK: "PLATZHALTER_PAYPAL_LINK",
  IBAN: "PLATZHALTER_IBAN",
  KONTOINHABER: "Christoph Aldering",
  BANK: "DKB",
  VERWENDUNGSZWECK_VORLAGE: "Boomerparty + dein Name",
  KONTAKT_MAIL: "boomerparty26@emmerich-boomt.de",
  MAX_PERSONEN_PRO_ANMELDUNG: 6,

  LETZTE_AENDERUNG: "16. Mai 2026",
};
