export const PHASE2_CONFIG = {
  ANMELDEFRIST: "Sonntag, 28. Juni 2026",
  ANMELDEFRIST_KURZ: "28.06.2026",
  PREIS_PRO_PERSON: 10,
  PAYPAL_LINK: "PLATZHALTER_PAYPAL_LINK",
  IBAN: "PLATZHALTER_IBAN",
  KONTOINHABER: "Christoph Aldering",
  BANK: "DKB",
  VERWENDUNGSZWECK_VORLAGE: "Boomerparty + dein Name",
  KONTAKT_MAIL: "tickets@emmerich-boomt.de",
  MAX_PERSONEN_PRO_ANMELDUNG: 6,
};
