kind = "web"
previewPath = "/"
title = "Emmerich boomt"
version = "1.0.0"
id = "artifacts/emmerich"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19937

[services.development]
run = "pnpm --filter @workspace/emmerich run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/emmerich", "run", "build" ]
publicDir = "artifacts/emmerich/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19937"
BASE_PATH = "/"
